### ISSUE TITLE
[Security Hardened Shoot Cluster] Add rule 1003 to check Lakom extension configuration

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/diki#431]
**What would you like to be added**:
A rule that checks if the Lakom extension is correctly configured should be added to the Security Hardened Shoot Cluster ruleset.

The Lakom extension should be configured with a reference to a secret with trusted keys.
``` yaml
spec:
  resources:
  - name: lakom-ref
    resourceRef:
      apiVersion: v1
      kind: Secret
      name: lakom-secret
  extensions:
  - type: shoot-lakom-service
    providerConfig:
      ...
      trustedKeysResourceName: lakom-ref
```

**Why is this needed**:
Enhance range of `Security Hardened Shoot Cluster` ruleset checks.
