### ISSUE TITLE
[Security Hardened Kubernetes Cluster] Improve rule 2000 to check for `default-allow` policy configured

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/diki#439]
**What would you like to be added**:
The Security Hardened Kubernetes Cluster rule 2000 should fail for namespaces that have a configured `default-allow` `NetworkPolicy` , since it would override any configured `default-deny` policies in the same namespace.

``` yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow
spec:
  # select all pods in the namespace
  podSelector: {}
  # allow all traffic
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
```

**Why is this needed**:
Configuring a `default-allow` `NetworkPolicy` overrides `default-deny` policies and does not follow the principles of least privilege.
