### ISSUE TITLE
Improve granularity of diki rule options

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/diki#472]
**What would you like to be added**:
Rule options should be revisited and where possible improve granularity of silence targets. For example rule 2001 of `security-hardened-k8s` should allow configuring accepted containers in addition to pods:
``` yaml
    - ruleID: "2001"
      args:
        acceptedPods:
        - matchLabels:
            foo: bar
          namespaceMatchLabels:
            foo: bar
          acceptedContainers: #improvement
          - foo
          justification: "justification"
``` 

**Why is this needed**:
Allow users to silence findings more precisely
