### ISSUE TITLE
Use `metav1.LabelSelector` for selector in rule options

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/diki#514]
**What would you like to be added**:
Currently for Rule options we are using a simple `MatchLabels` map to match Kubernetes options. e.g.:

``` yaml
  acceptedPods:
  - matchLabels:
      foo: bar
    namespaceMatchLabels:
      kubernetes.io/metadata.name: default
```

`MatchLabels` is limited to only the `In` operator and only to a single value, I would like for diki to use `metav1.LabelSelector` for Rule Options, which also uses `MatchLabels`, however it also has `MatchExpressions` which utilizes the `In`, `NotIn`, `Exists` and `DoesNotExist` operators. This would improve the process of writing diki options. e.g.:

``` yaml
  acceptedPods:
  - labelSelector:
      matchExpressions:
        - key: foo
          operator: In
          values:
          - bar
          - baz
          - qux
    namespaceLabelSelector:
      matchLabels:
        kubernetes.io/metadata.name: default
```

When we implement `labelSelectors` we should deprecate `matchLabels` (it would be used only if `labelSelectors` is not configured in the specific rule option) and remove it in a future release.

## Action items

- [x] https://github.com/gardener/diki/pull/515
- [x] https://github.com/gardener/diki/pull/589
- [x] https://github.com/gardener/diki/pull/590
- [x] https://github.com/gardener/diki/pull/594
- [x] https://github.com/gardener/diki/pull/595
- [x] https://github.com/gardener/diki/pull/598
